In [4]:
import numpy as np
import pandas as pd

### **Creating Data Frame objects using function**

In [2]:
def df(nRows, mCols, maxRand):
    arr = np.random.randint(0, maxRand, (nRows, mCols))
    df = pd.DataFrame(arr)
    df.index = ['R' + str(x) for x in np.arange(1, nRows + 1)]
    df.columns = ['C' + str(x) for x in np.arange(1, mCols + 1)]
    return df

In [3]:
df(4, 6, 16)

    C1  C2  C3  C4  C5  C6
R1   0  12  14   2   9  14
R2   3  14   2   8   0  15
R3   6   2   7   8   0   2
R4   0   0  10   5   1  11

In [4]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146], 
                 index=['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])
diameter = pd.Series([4879, 12104, 12756, 3475, 6792, 142984, 120536, 51118, 49528, 2370], 
                     index=['Mercury', 'Venus', 'Earth', 'Moon', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])

In [5]:
mass

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
dtype: float64

In [6]:
diameter

Mercury      4879
Venus       12104
Earth       12756
Moon         3475
Mars         6792
Jupiter    142984
Saturn     120536
Uranus      51118
Neptune     49528
Pluto        2370
dtype: int64

In [7]:
df = pd.DataFrame({'mass' : mass, 'diameter' : diameter})

In [8]:
df

              mass  diameter
Earth       5.9700     12756
Jupiter  1898.0000    142984
Mars        0.6420      6792
Mercury     0.3300      4879
Moon           NaN      3475
Neptune   102.0000     49528
Pluto       0.0146      2370
Saturn    568.0000    120536
Uranus     86.8000     51118
Venus       4.8700     12104

In [9]:
df['diameter']

Earth       12756
Jupiter    142984
Mars         6792
Mercury      4879
Moon         3475
Neptune     49528
Pluto        2370
Saturn     120536
Uranus      51118
Venus       12104
Name: diameter, dtype: int64

In [10]:
df

              mass  diameter
Earth       5.9700     12756
Jupiter  1898.0000    142984
Mars        0.6420      6792
Mercury     0.3300      4879
Moon           NaN      3475
Neptune   102.0000     49528
Pluto       0.0146      2370
Saturn    568.0000    120536
Uranus     86.8000     51118
Venus       4.8700     12104

In [11]:
def create_mean(df):
    df.loc['column_mean'] = df.mean()
    df['Row_mean'] = df.mean(axis = 1)
    return df

In [12]:
create_mean(df)

                    mass  diameter      Row_mean
Earth           5.970000   12756.0   6380.985000
Jupiter      1898.000000  142984.0  72441.000000
Mars            0.642000    6792.0   3396.321000
Mercury         0.330000    4879.0   2439.665000
Moon                 NaN    3475.0   3475.000000
Neptune       102.000000   49528.0  24815.000000
Pluto           0.014600    2370.0   1185.007300
Saturn        568.000000  120536.0  60552.000000
Uranus         86.800000   51118.0  25602.400000
Venus           4.870000   12104.0   6054.435000
column_mean   296.291844   40654.2  20475.245922

In [13]:
print(df.describe)

<bound method NDFrame.describe of                     mass  diameter      Row_mean
Earth           5.970000   12756.0   6380.985000
Jupiter      1898.000000  142984.0  72441.000000
Mars            0.642000    6792.0   3396.321000
Mercury         0.330000    4879.0   2439.665000
Moon                 NaN    3475.0   3475.000000
Neptune       102.000000   49528.0  24815.000000
Pluto           0.014600    2370.0   1185.007300
Saturn        568.000000  120536.0  60552.000000
Uranus         86.800000   51118.0  25602.400000
Venus           4.870000   12104.0   6054.435000
column_mean   296.291844   40654.2  20475.245922>

In [14]:
df.describe()

              mass       diameter      Row_mean
count    10.000000      11.000000     11.000000
mean    296.291844   40654.200000  20619.732657
std     591.882722   48896.457198  24568.636205
min       0.014600    2370.000000   1185.007300
25%       1.699000    5835.500000   3435.660500
50%      46.385000   12756.000000   6380.985000
75%     247.718883   50323.000000  25208.700000
max    1898.000000  142984.000000  72441.000000

In [15]:
import seaborn as sns

In [16]:
planets = sns.load_dataset('planets')

In [17]:
planets

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [18]:
planets.head(10)

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009
5  Radial Velocity       1         185.840   4.80     76.39  2008
6  Radial Velocity       1        1773.400   4.64     18.15  2002
7  Radial Velocity       1         798.500    NaN     21.41  1996
8  Radial Velocity       1         993.300  10.30     73.10  2008
9  Radial Velocity       2         452.800   1.99     74.79  2010

In [19]:
planets.tail(10)

       method  number  orbital_period  mass  distance  year
1025  Transit       1        3.067850   NaN      60.0  2012
1026  Transit       1        0.925542   NaN     470.0  2014
1027  Imaging       1             NaN   NaN      19.2  2011
1028  Transit       1        3.352057   NaN    3200.0  2012
1029  Imaging       1             NaN   NaN      10.1  2012
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [20]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

In [21]:
planets.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

# Dropping Rows with null values


<font color = 'red'> ***Going through each row of the dataframe and deleting if any of the columns is null***

## Method 1: conventional way of dropping row if it has null values

In [22]:
for r in planets.index:
    for c in planets.columns:
        if pd.isnull(planets.loc[r, c]):
            planets.drop(r, inplace = True)
            break

In [23]:
planets.describe

<bound method NDFrame.describe of               method  number  orbital_period    mass  distance  year
0    Radial Velocity       1       269.30000   7.100     77.40  2006
1    Radial Velocity       1       874.77400   2.210     56.95  2008
2    Radial Velocity       1       763.00000   2.600     19.84  2011
3    Radial Velocity       1       326.03000  19.400    110.62  2007
4    Radial Velocity       1       516.22000  10.500    119.47  2009
..               ...     ...             ...     ...       ...   ...
640  Radial Velocity       1       111.70000   2.100     14.90  2009
641  Radial Velocity       1         5.05050   1.068     44.46  2013
642  Radial Velocity       1       311.28800   1.940     17.24  1999
649          Transit       1         2.70339   1.470    178.00  2013
784  Radial Velocity       3       580.00000   0.947    135.00  2012

[498 rows x 6 columns]>

##Method 2: Faster way of dropping row having null values

In [24]:
planets = sns.load_dataset('planets')

In [25]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

In [26]:
for i, r in planets.iterrows():
    if pd.isnull(r).any():
        planets.drop(i, inplace = True)

In [27]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 498 entries, 0 to 784
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          498 non-null    object
 1   number          498 non-null    int64
 2   orbital_period  498 non-null    float64
 3   mass            498 non-null    float64
 4   distance        498 non-null    float64
 5   year            498 non-null    int64
dtypes: float64(3), int64(2), object(1)
memory usage: 27.2+ KB

## Method 3: Ultimate faster way of droppinng row having null values

In [28]:
planets = sns.load_dataset('planets')

In [29]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

In [30]:
planets.dropna(inplace = True)

In [31]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 498 entries, 0 to 784
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          498 non-null    object
 1   number          498 non-null    int64
 2   orbital_period  498 non-null    float64
 3   mass            498 non-null    float64
 4   distance        498 non-null    float64
 5   year            498 non-null    int64
dtypes: float64(3), int64(2), object(1)
memory usage: 27.2+ KB

 # **Filtering Dataset**

Filter and show only those rows which have planets that are found in the 2010's and method is 'Radial Velocity' and 'Transit' and distance is large (>=75 percentile)

In [32]:
planets_copy = planets.copy()

In [33]:
percentile_75 = planets['distance'].quantile(0.75)

In [34]:
percentile_75

59.3325

In [35]:
 for i, r in planets_copy.iterrows():
     if r['year'] < 2010:
         planets_copy.drop(i, inplace = True)
         continue
     if r['method'] != 'Radial Velocity' and r['method'] != 'Transit':
         planets_copy.drop(i, inplace = True)
         continue
     if r['distance'] < percentile_75:
         planets_copy.drop(i, inplace = True)
         continue

In [36]:
planets_copy

              method  number  orbital_period    mass  distance  year
9    Radial Velocity       2       452.80000   1.990     74.79  2010
10   Radial Velocity       2       883.00000   0.860     74.79  2010
58   Radial Velocity       1       277.02000   1.700     80.64  2013
63   Radial Velocity       1       305.50000  20.600     92.51  2013
84   Radial Velocity       1       137.48000   1.110    175.44  2013
166  Radial Velocity       2      5584.00000   3.400     90.00  2010
181  Radial Velocity       2      1022.00000   3.400    354.00  2011
202  Radial Velocity       1       431.80000   3.100    167.50  2011
206  Radial Velocity       1       311.60000   1.600    115.21  2013
218  Radial Velocity       1       177.11000   7.600    150.60  2011
248  Radial Velocity       2        19.38200   0.865     66.89  2013
249  Radial Velocity       2       931.00000   5.130     66.89  2013
257  Radial Velocity       1       772.00000   2.700    127.88  2011
282  Radial Velocity       1       387.10000   1.700    168.92  2011
285  Radial Velocity       1       912.00000   1.800    121.07  2011
290  Radial Velocity       1       326.60000   1.300    136.80  2011
349  Radial Velocity       1       480.50000   6.000     80.06  2012
376  Radial Velocity       1       705.00000   1.300    112.23  2011
394  Radial Velocity       1       361.10000   0.900    132.80  2011
396  Radial Velocity       1       647.30000   4.000    221.24  2011
400  Radial Velocity       1       436.90000   1.800    150.38  2011
405  Radial Velocity       1       868.00000   1.400    130.89  2011
406  Radial Velocity       1       157.57000   1.700    140.85  2011
414  Radial Velocity       1       778.10000   5.900    138.50  2011
415  Radial Velocity       1         6.49500   0.960    121.07  2010
421  Radial Velocity       1      2890.00000  11.000     87.87  2011
426  Radial Velocity       1       443.40000   2.600    138.50  2011
429  Radial Velocity       1        68.27000   0.770     65.62  2010
444  Radial Velocity       1       670.00000   2.100    110.62  2011
448  Radial Velocity       1      2082.00000   4.500     97.66  2013
461  Radial Velocity       1       883.00000   2.200    121.36  2011
464  Radial Velocity       1      1544.00000   1.490     98.52  2011
480  Radial Velocity       1      1299.00000   1.900    106.38  2011
483  Radial Velocity       1       176.30000   2.900    126.10  2010
495  Radial Velocity       1       689.00000   1.500    182.82  2011
501  Radial Velocity       2      3452.00000   2.580     68.54  2014
509  Radial Velocity       1       521.00000   1.800    114.15  2011
510  Radial Velocity       2        12.62000   1.130     68.59  2013
511  Radial Velocity       2       248.40000   1.900     68.59  2013
519  Radial Velocity       2        75.29000   0.770     69.44  2010
520  Radial Velocity       2      1314.00000   2.290     69.44  2010
573  Radial Velocity       2       613.80000   1.850     68.35  2010
574  Radial Velocity       2       825.00000   0.895     68.35  2010
587  Radial Velocity       1       875.50000   9.900    352.11  2012
610  Radial Velocity       1       672.10000  11.100    289.02  2012
620  Radial Velocity       1       745.70000   5.300    307.69  2011
627  Radial Velocity       1        16.20000   1.250    223.21  2010
636  Radial Velocity       1       124.60000   9.180    149.25  2013
649          Transit       1         2.70339   1.470    178.00  2013
784  Radial Velocity       3       580.00000   0.947    135.00  2012

In [37]:
planets_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 9 to 784
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          50 non-null     object
 1   number          50 non-null     int64
 2   orbital_period  50 non-null     float64
 3   mass            50 non-null     float64
 4   distance        50 non-null     float64
 5   year            50 non-null     int64
dtypes: float64(3), int64(2), object(1)
memory usage: 2.7+ KB

In [38]:
df = sns.load_dataset('planets')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

In [40]:
df = df.copy()
df = df[
        (df['year'] >= 2010) &
        ((df['method'] == 'Transit') | (df['method'] == 'Radial Velocity')) &
        (df['distance'] > percentile_75)
        ]

In [41]:
df.describe()

           number  orbital_period       mass     distance         year
count  230.000000      230.000000  50.000000   230.000000   230.000000
mean     1.817391      192.314565   3.322740   474.566043  2011.417391
std      1.575371      544.970903   3.648002   502.143254     1.093711
min      1.000000        0.742960   0.770000    60.000000  2010.000000
25%      1.000000        3.535516   1.325000   135.450000  2011.000000
50%      1.000000        7.882643   1.875000   303.000000  2011.000000
75%      2.000000      124.046850   3.400000   613.000000  2012.000000
max      7.000000     5584.000000  20.600000  3200.000000  2014.000000

In [42]:
df = sns.load_dataset('planets')

In [43]:
df['method'].unique()

array(['Radial Velocity', 'Imaging', 'Eclipse Timing Variations',
       'Transit', 'Astrometry', 'Transit Timing Variations',
       'Orbital Brightness Modulation', 'Microlensing', 'Pulsar Timing',
       'Pulsation Timing Variations'], dtype=object)

In [44]:
s = df['method'].unique()

In [45]:
short_names = {}
for i in s:
    short_names[i] = ''.join([x[0] for x in i.split(' ')])

In [46]:
short_names

{'Astrometry': 'A',
 'Eclipse Timing Variations': 'ETV',
 'Imaging': 'I',
 'Microlensing': 'M',
 'Orbital Brightness Modulation': 'OBM',
 'Pulsar Timing': 'PT',
 'Pulsation Timing Variations': 'PTV',
 'Radial Velocity': 'RV',
 'Transit': 'T',
 'Transit Timing Variations': 'TTV'}

In [47]:
for i, r in df.iterrows():
    df.loc[i, 'short_method'] = short_names.get(r['method'], r['method'])

In [48]:
df

               method  number  orbital_period  ...  distance  year  short_method
0     Radial Velocity       1      269.300000  ...     77.40  2006            RV
1     Radial Velocity       1      874.774000  ...     56.95  2008            RV
2     Radial Velocity       1      763.000000  ...     19.84  2011            RV
3     Radial Velocity       1      326.030000  ...    110.62  2007            RV
4     Radial Velocity       1      516.220000  ...    119.47  2009            RV
...               ...     ...             ...  ...       ...   ...           ...
1030          Transit       1        3.941507  ...    172.00  2006             T
1031          Transit       1        2.615864  ...    148.00  2007             T
1032          Transit       1        3.191524  ...    174.00  2007             T
1033          Transit       1        4.125083  ...    293.00  2008             T
1034          Transit       1        4.187757  ...    260.00  2008             T

[1035 rows x 7 columns]

In [49]:
df_copy = sns.load_dataset('planets')

In [50]:
def shorten_method(s):
    return short_names.get(s, s)

In [51]:
df.loc['short_method'] = df['method'].apply(shorten_method)

In [52]:
df

                       method  number  ...    year  short_method
0             Radial Velocity     1.0  ...  2006.0            RV
1             Radial Velocity     1.0  ...  2008.0            RV
2             Radial Velocity     1.0  ...  2011.0            RV
3             Radial Velocity     1.0  ...  2007.0            RV
4             Radial Velocity     1.0  ...  2009.0            RV
...                       ...     ...  ...     ...           ...
1031                  Transit     1.0  ...  2007.0             T
1032                  Transit     1.0  ...  2007.0             T
1033                  Transit     1.0  ...  2008.0             T
1034                  Transit     1.0  ...  2008.0             T
short_method              NaN     NaN  ...     NaN           NaN

[1036 rows x 7 columns]

count the number of planets discoverd for each method type

In [54]:
df['method'].count()

1035

In [60]:
d = {}
for i in df['method'].unique():
    d[i] = (df[df['method'] == i]['method'].count()) 
print(d)

{'Radial Velocity': 553, 'Imaging': 38, 'Eclipse Timing Variations': 9, 'Transit': 397, 'Astrometry': 2, 'Transit Timing Variations': 4, 'Orbital Brightness Modulation': 3, 'Microlensing': 23, 'Pulsar Timing': 5, 'Pulsation Timing Variations': 1, nan: 0}

In [63]:
df.groupby('method')['method'].count()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
Name: method, dtype: int64

Find out what fraction of planets have been found in the last decade (i.e., in 2010s) across each method type

In [72]:
x = df[df['year'] >= 2010].groupby('method')['method'].count()

In [73]:
y = df.groupby('method')['method'].count()

In [74]:
x/y

method
Astrometry                       1.000000
Eclipse Timing Variations        0.666667
Imaging                          0.473684
Microlensing                     0.565217
Orbital Brightness Modulation    1.000000
Pulsar Timing                    0.200000
Pulsation Timing Variations           NaN
Radial Velocity                  0.388788
Transit                          0.843829
Transit Timing Variations        1.000000
Name: method, dtype: float64